# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretsanta', '0002_auto_20161212_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='secret_key',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
