# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretsanta', '0003_auto_20161212_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='secret_key',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
